safe: true
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'serve.sh', 'article.png', 'LICENSE']
baseurl: /paper-now
collections:
    figures:
        output: true
        title: 'Figures'
    tables:
        output: true
        title: 'Tables'
    sections:
        output: true
