safe: true
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'serve.sh', 'article.png', 'LICENSE']
baseurl: /paper-now
javascripts:
    mathjax: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML,Safe
    hypothesis: https://hypothes.is/embed.js
    #d3: https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js
collections:
    figures:
        output: true
        title: 'Figures'
    tables:
        output: true
        title: 'Tables'
    sections:
        output: true
