safe: true
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'serve.sh', 'article.png', 'LICENSE']
baseurl: /paper-now
imports:
    - https://peerj.github.io/research-article/research-article.html
theme: https://peerj.github.io/paper-themes/paper-now/
collections:
    figures:
        output: true
        title: 'Figures'
    tables:
        output: true
        title: 'Tables'
    sections:
        output: true
